version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  # db:
  #   image: sqlite3
  #   environment:
  #     - SQLITE3_DB=sqlite3
  #     - SQLITE3_USER=admin
  #     - SQLITE3_PASSWORD=admin
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db