# Generated by Django 2.2.5 on 2020-10-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('regular_price_value', models.CharField(max_length=60, null=True)),
                ('offer_price_value', models.CharField(max_length=60, null=True)),
                ('currency', models.CharField(max_length=60, null=True)),
                ('classification_l1', models.CharField(max_length=60, null=True)),
                ('classification_l2', models.CharField(max_length=60, null=True)),
                ('classification_l3', models.CharField(max_length=60, null=True)),
                ('classification_l4', models.CharField(max_length=60, null=True)),
                ('image_url', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
