# Generated by Django 3.0.1 on 2020-11-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
