# Generated by Django 3.0.1 on 2020-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0004_auto_20201101_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='brand_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='classification_l1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='classification_l2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='classification_l3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='classification_l4',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='currency',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='image_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='offer_price_value',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='regular_price_value',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
