# Generated by Django 3.0.1 on 2020-11-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0005_auto_20201101_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
